/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertException: typeof import('./components/exception/AlertException.vue')['default']
    Apartamento: typeof import('./components/page-component/endereco/apartamento.vue')['default']
    Condominio: typeof import('./components/page-component/endereco/condominio.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
